package viewpackage;

//import javax.swing.JFrame; 

import java.awt.Color;



/**
 *
 * @author elisha
 */
public class mainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainFrame.class.getName());

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH); // code making the frame full screen
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstLayer = new javax.swing.JPanel();
        navigationpanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        dasboardButton = new javax.swing.JButton();
        logoInFull = new javax.swing.JLabel();
        dasboardButton1 = new javax.swing.JButton();
        recordDailySales_btn = new javax.swing.JButton();
        dasboardButton3 = new javax.swing.JButton();
        dasboardButton4 = new javax.swing.JButton();
        dasboardButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        versionLabel = new javax.swing.JLabel();
        motherTab = new javax.swing.JTabbedPane();
        dashboardTab = new javax.swing.JPanel();
        dashboardLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1570, 900));
        setResizable(false);

        firstLayer.setBackground(new java.awt.Color(102, 102, 0));
        firstLayer.setDoubleBuffered(false);
        firstLayer.setPreferredSize(new java.awt.Dimension(1800, 990));
        firstLayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navigationpanel.setBackground(new java.awt.Color(255, 255, 255));

        logoLabel.setFont(new java.awt.Font("Liberation Sans", 1, 98)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(44, 62, 80));
        logoLabel.setText("RSM");
        logoLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 62, 80), 4, true));

        dasboardButton.setBackground(new java.awt.Color(52, 73, 94));
        dasboardButton.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        dasboardButton.setForeground(new java.awt.Color(255, 255, 255));
        dasboardButton.setText("Home");

        logoInFull.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        logoInFull.setForeground(new java.awt.Color(243, 156, 18));
        logoInFull.setText("-- Retail Shop Manager --");

        dasboardButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        dasboardButton1.setText("View Stock Summary");
        dasboardButton1.setAutoscrolls(true);

        recordDailySales_btn.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        recordDailySales_btn.setText("Record Daily Sales");
        recordDailySales_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recordDailySales_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recordDailySales_btnMouseExited(evt);
            }
        });

        dasboardButton3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        dasboardButton3.setLabel("Record Purchases (Stock In)");

        dasboardButton4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        dasboardButton4.setText("Record Expenses");
        dasboardButton4.setAutoscrolls(true);

        dasboardButton5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        dasboardButton5.setText("View Weekly Report");
        dasboardButton5.setAutoscrolls(true);

        jButton1.setBackground(new java.awt.Color(231, 76, 60));
        jButton1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");

        versionLabel.setFont(new java.awt.Font("Noto Sans Display", 0, 15)); // NOI18N
        versionLabel.setText("Version 0.2");

        javax.swing.GroupLayout navigationpanelLayout = new javax.swing.GroupLayout(navigationpanel);
        navigationpanel.setLayout(navigationpanelLayout);
        navigationpanelLayout.setHorizontalGroup(
            navigationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(navigationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoInFull, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(navigationpanelLayout.createSequentialGroup()
                .addGroup(navigationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navigationpanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(navigationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dasboardButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(recordDailySales_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dasboardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dasboardButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dasboardButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dasboardButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(navigationpanelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(versionLabel)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        navigationpanelLayout.setVerticalGroup(
            navigationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationpanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoInFull)
                .addGap(49, 49, 49)
                .addComponent(dasboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(recordDailySales_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dasboardButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dasboardButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dasboardButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dasboardButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(versionLabel)
                .addGap(21, 21, 21))
        );

        firstLayer.add(navigationpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 900));

        motherTab.setBackground(new java.awt.Color(51, 0, 204));

        dashboardTab.setBackground(new java.awt.Color(52, 73, 94));

        dashboardLabel.setBackground(new java.awt.Color(236, 240, 241));
        dashboardLabel.setFont(new java.awt.Font("URW Bookman", 1, 45)); // NOI18N
        dashboardLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardLabel.setText("Dashboard");

        javax.swing.GroupLayout dashboardTabLayout = new javax.swing.GroupLayout(dashboardTab);
        dashboardTab.setLayout(dashboardTabLayout);
        dashboardTabLayout.setHorizontalGroup(
            dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardTabLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(dashboardLabel)
                .addContainerGap(973, Short.MAX_VALUE))
        );
        dashboardTabLayout.setVerticalGroup(
            dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardTabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(dashboardLabel)
                .addContainerGap(793, Short.MAX_VALUE))
        );

        motherTab.addTab("dashboard", dashboardTab);

        jPanel4.setBackground(new java.awt.Color(52, 73, 94));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
        );

        motherTab.addTab("tab2", jPanel4);

        firstLayer.add(motherTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 1270, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(firstLayer, javax.swing.GroupLayout.PREFERRED_SIZE, 1599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(firstLayer, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//    Hover effect on buttons
    private void recordDailySales_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordDailySales_btnMouseEntered
       recordDailySales_btn.setBackground(Color.GREEN);
       recordDailySales_btn.setForeground(Color.white);
    }//GEN-LAST:event_recordDailySales_btnMouseEntered

    private void recordDailySales_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordDailySales_btnMouseExited
        recordDailySales_btn.setBackground(Color.white);
        recordDailySales_btn.setForeground(Color.black);
    }//GEN-LAST:event_recordDailySales_btnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dasboardButton;
    private javax.swing.JButton dasboardButton1;
    private javax.swing.JButton dasboardButton3;
    private javax.swing.JButton dasboardButton4;
    private javax.swing.JButton dasboardButton5;
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JPanel dashboardTab;
    private javax.swing.JPanel firstLayer;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logoInFull;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JTabbedPane motherTab;
    private javax.swing.JPanel navigationpanel;
    private javax.swing.JButton recordDailySales_btn;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
}
