package viewpackage;

//import javax.swing.JFrame; 

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;



/**
 *
 * @author elisha
 */
public class mainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainFrame.class.getName());

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH); // code making the frame full screen
        
//      Calling buttonEffectCall() function to create the button effects
        buttonEffectCall();

//        Home button active at the start of the program
        activeButton = dashboardButton;
        dashboardButton.setBackground(new Color(52,73,94));
    }
    
    /*
    * method calling the setupbutton method and passing arguments [button variable name] 
    */

    private void buttonEffectCall(){
        setupButton(dashboardButton, 0);
        setupButton(recordDailySales_btn, 1);
        setupButton(recordPurchases_btn,2);
        setupButton(recordExpenses_btn,3);
        setupButton(viewWeeklyReport_btn,4);
        setupButton(viewStockSummary_btn,5);
    }
    
    
    JButton activeButton = null; // Global variable to keep track of the active button

    /*
    *   This function is handling the hover and active button effects 
    */
    private void setupButton(JButton button, int tabIndex) {
        Color defaultColor = new Color(240, 240, 240); // Default button color
        String hoverColor = "#324A69"; // Hover color
        String activeColor = "#34495E"; // Active color

        button.setBackground(defaultColor);

        button.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                if (button != activeButton) {
                    button.setBackground(Color.decode(hoverColor));
                    button.setForeground(Color.white);
                }
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                if (button != activeButton) {
                    button.setBackground(defaultColor);
                    button.setForeground(Color.black);
                }
            }

            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // Reset previous active button
                if (activeButton != null && activeButton != button) {
                    activeButton.setBackground(defaultColor);
                    activeButton.setForeground(Color.black);
                }

                // Set this button as active
                activeButton = button;
                activeButton.setBackground(Color.decode(activeColor));
                activeButton.setForeground(Color.white);
                motherTab.setSelectedIndex(tabIndex);
            }
        });
    }

    
//    get boolean variable to store the active button. the button that is active will have a true when clicked
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstLayer = new javax.swing.JPanel();
        navigationpanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        dashboardButton = new javax.swing.JButton();
        logoInFull = new javax.swing.JLabel();
        viewStockSummary_btn = new javax.swing.JButton();
        recordDailySales_btn = new javax.swing.JButton();
        recordPurchases_btn = new javax.swing.JButton();
        recordExpenses_btn = new javax.swing.JButton();
        viewWeeklyReport_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        versionLabel = new javax.swing.JLabel();
        motherTab = new javax.swing.JTabbedPane();
        dashboardTab = new javax.swing.JPanel();
        dashboardLabel = new javax.swing.JLabel();
        recordDailySales = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cashout_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dailyCashout_tbl = new javax.swing.JTable();
        sorting_combobox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        weekly_cashout_summary_label = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        monthly_sales_summary_label = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        recordPurchases = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        recordExpenses = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        viewWeeklyReport = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        stockTab = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1570, 900));
        setResizable(false);

        firstLayer.setBackground(new java.awt.Color(102, 102, 0));
        firstLayer.setDoubleBuffered(false);
        firstLayer.setPreferredSize(new java.awt.Dimension(1800, 990));
        firstLayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navigationpanel.setBackground(new java.awt.Color(255, 255, 255));

        logoLabel.setFont(new java.awt.Font("Liberation Sans", 1, 98)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(44, 62, 80));
        logoLabel.setText("RSM");
        logoLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(44, 62, 80), 4, true));

        dashboardButton.setBackground(new java.awt.Color(52, 73, 94));
        dashboardButton.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        dashboardButton.setForeground(new java.awt.Color(255, 255, 255));
        dashboardButton.setText("Home");

        logoInFull.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        logoInFull.setForeground(new java.awt.Color(243, 156, 18));
        logoInFull.setText("-- Retail Shop Manager --");

        viewStockSummary_btn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        viewStockSummary_btn.setText("View Stock Summary");
        viewStockSummary_btn.setAutoscrolls(true);
        viewStockSummary_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewStockSummary_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewStockSummary_btnMouseExited(evt);
            }
        });

        recordDailySales_btn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        recordDailySales_btn.setText("Record Daily Sales");
        recordDailySales_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recordDailySales_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recordDailySales_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recordDailySales_btnMouseExited(evt);
            }
        });

        recordPurchases_btn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        recordPurchases_btn.setLabel("Record Purchases (Stock In)");
        recordPurchases_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recordPurchases_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recordPurchases_btnMouseExited(evt);
            }
        });

        recordExpenses_btn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        recordExpenses_btn.setText("Record Expenses");
        recordExpenses_btn.setAutoscrolls(true);
        recordExpenses_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recordExpenses_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recordExpenses_btnMouseExited(evt);
            }
        });

        viewWeeklyReport_btn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        viewWeeklyReport_btn.setText("View Weekly Report");
        viewWeeklyReport_btn.setAutoscrolls(true);
        viewWeeklyReport_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewWeeklyReport_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewWeeklyReport_btnMouseExited(evt);
            }
        });

        logout_btn.setBackground(new java.awt.Color(231, 76, 60));
        logout_btn.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(255, 255, 255));
        logout_btn.setText("Logout");
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_btnMouseExited(evt);
            }
        });

        versionLabel.setFont(new java.awt.Font("Noto Sans Display", 0, 15)); // NOI18N
        versionLabel.setText("Version 0.2");

        javax.swing.GroupLayout navigationpanelLayout = new javax.swing.GroupLayout(navigationpanel);
        navigationpanel.setLayout(navigationpanelLayout);
        navigationpanelLayout.setHorizontalGroup(
            navigationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(navigationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoInFull, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
            .addGroup(navigationpanelLayout.createSequentialGroup()
                .addGroup(navigationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navigationpanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(navigationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewStockSummary_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(recordDailySales_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dashboardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(recordPurchases_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(recordExpenses_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewWeeklyReport_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(navigationpanelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(versionLabel)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        navigationpanelLayout.setVerticalGroup(
            navigationpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationpanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoInFull)
                .addGap(49, 49, 49)
                .addComponent(dashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(recordDailySales_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(recordPurchases_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(recordExpenses_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewWeeklyReport_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewStockSummary_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(versionLabel)
                .addGap(21, 21, 21))
        );

        firstLayer.add(navigationpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 900));

        motherTab.setBackground(new java.awt.Color(51, 0, 204));

        dashboardTab.setBackground(new java.awt.Color(52, 73, 94));

        dashboardLabel.setBackground(new java.awt.Color(236, 240, 241));
        dashboardLabel.setFont(new java.awt.Font("URW Bookman", 1, 45)); // NOI18N
        dashboardLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardLabel.setText("Dashboard");

        javax.swing.GroupLayout dashboardTabLayout = new javax.swing.GroupLayout(dashboardTab);
        dashboardTab.setLayout(dashboardTabLayout);
        dashboardTabLayout.setHorizontalGroup(
            dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardTabLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(dashboardLabel)
                .addContainerGap(977, Short.MAX_VALUE))
        );
        dashboardTabLayout.setVerticalGroup(
            dashboardTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardTabLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(dashboardLabel)
                .addContainerGap(800, Short.MAX_VALUE))
        );

        motherTab.addTab("dashboard", dashboardTab);

        recordDailySales.setBackground(new java.awt.Color(52, 73, 94));

        jLabel1.setBackground(new java.awt.Color(236, 240, 241));
        jLabel1.setFont(new java.awt.Font("URW Bookman", 1, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Record Daily Sales (CashOut)");

        cashout_btn.setBackground(new java.awt.Color(13, 107, 53));
        cashout_btn.setFont(new java.awt.Font("URW Bookman", 1, 36)); // NOI18N
        cashout_btn.setForeground(new java.awt.Color(255, 255, 255));
        cashout_btn.setText("+ Register Cashout");

        dailyCashout_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Amount (shs)", "Action"
            }
        ));
        jScrollPane1.setViewportView(dailyCashout_tbl);

        sorting_combobox.setFont(new java.awt.Font("URW Bookman", 0, 18)); // NOI18N
        sorting_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort By", "Most Recent", "Oldest" }));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(241, 196, 15), 6, true));

        jLabel7.setFont(new java.awt.Font("URW Bookman", 1, 27)); // NOI18N
        jLabel7.setText("SALES SUMARY");

        weekly_cashout_summary_label.setFont(new java.awt.Font("URW Bookman", 1, 18)); // NOI18N
        weekly_cashout_summary_label.setForeground(new java.awt.Color(39, 174, 96));
        weekly_cashout_summary_label.setText("Shs. 1,845,000");

        jLabel9.setFont(new java.awt.Font("URW Bookman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(44, 62, 80));
        jLabel9.setText("Weekly Sales Total");

        monthly_sales_summary_label.setFont(new java.awt.Font("URW Bookman", 1, 18)); // NOI18N
        monthly_sales_summary_label.setForeground(new java.awt.Color(39, 174, 96));
        monthly_sales_summary_label.setText("Shs. 6,845,000");

        jLabel11.setFont(new java.awt.Font("URW Bookman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(44, 62, 80));
        jLabel11.setText("Monthly Sales Total");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monthly_sales_summary_label)
                            .addComponent(jLabel11)
                            .addComponent(weekly_cashout_summary_label))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel9)
                    .addContainerGap(53, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(weekly_cashout_summary_label)
                .addGap(39, 39, 39)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monthly_sales_summary_label)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(jLabel9)
                    .addContainerGap(150, Short.MAX_VALUE)))
        );

        jLabel8.setFont(new java.awt.Font("URW Bookman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setText("Recent Records");

        javax.swing.GroupLayout recordDailySalesLayout = new javax.swing.GroupLayout(recordDailySales);
        recordDailySales.setLayout(recordDailySalesLayout);
        recordDailySalesLayout.setHorizontalGroup(
            recordDailySalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordDailySalesLayout.createSequentialGroup()
                .addGroup(recordDailySalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recordDailySalesLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(recordDailySalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(recordDailySalesLayout.createSequentialGroup()
                                .addGroup(recordDailySalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sorting_combobox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 861, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(recordDailySalesLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(cashout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(recordDailySalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(recordDailySalesLayout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jLabel8)
                    .addContainerGap(1019, Short.MAX_VALUE)))
        );
        recordDailySalesLayout.setVerticalGroup(
            recordDailySalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordDailySalesLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(cashout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(sorting_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(recordDailySalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(recordDailySalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(recordDailySalesLayout.createSequentialGroup()
                    .addGap(310, 310, 310)
                    .addComponent(jLabel8)
                    .addContainerGap(565, Short.MAX_VALUE)))
        );

        motherTab.addTab("recordDailySales", recordDailySales);

        recordPurchases.setBackground(new java.awt.Color(52, 73, 94));

        jLabel2.setText("2");

        javax.swing.GroupLayout recordPurchasesLayout = new javax.swing.GroupLayout(recordPurchases);
        recordPurchases.setLayout(recordPurchasesLayout);
        recordPurchasesLayout.setHorizontalGroup(
            recordPurchasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordPurchasesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addContainerGap(1217, Short.MAX_VALUE))
        );
        recordPurchasesLayout.setVerticalGroup(
            recordPurchasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordPurchasesLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addContainerGap(838, Short.MAX_VALUE))
        );

        motherTab.addTab("purchaseRecords", recordPurchases);

        recordExpenses.setBackground(new java.awt.Color(52, 73, 94));

        jLabel3.setText("3");

        javax.swing.GroupLayout recordExpensesLayout = new javax.swing.GroupLayout(recordExpenses);
        recordExpenses.setLayout(recordExpensesLayout);
        recordExpensesLayout.setHorizontalGroup(
            recordExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordExpensesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addContainerGap(1217, Short.MAX_VALUE))
        );
        recordExpensesLayout.setVerticalGroup(
            recordExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordExpensesLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addContainerGap(838, Short.MAX_VALUE))
        );

        motherTab.addTab("recordExpenses", recordExpenses);

        viewWeeklyReport.setBackground(new java.awt.Color(52, 73, 94));

        jLabel4.setText("4");

        javax.swing.GroupLayout viewWeeklyReportLayout = new javax.swing.GroupLayout(viewWeeklyReport);
        viewWeeklyReport.setLayout(viewWeeklyReportLayout);
        viewWeeklyReportLayout.setHorizontalGroup(
            viewWeeklyReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewWeeklyReportLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel4)
                .addContainerGap(1217, Short.MAX_VALUE))
        );
        viewWeeklyReportLayout.setVerticalGroup(
            viewWeeklyReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewWeeklyReportLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel4)
                .addContainerGap(838, Short.MAX_VALUE))
        );

        motherTab.addTab("viewWeeklyReport", viewWeeklyReport);

        stockTab.setBackground(new java.awt.Color(52, 73, 94));

        jLabel5.setText("5");

        javax.swing.GroupLayout stockTabLayout = new javax.swing.GroupLayout(stockTab);
        stockTab.setLayout(stockTabLayout);
        stockTabLayout.setHorizontalGroup(
            stockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockTabLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel5)
                .addContainerGap(1217, Short.MAX_VALUE))
        );
        stockTabLayout.setVerticalGroup(
            stockTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockTabLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel5)
                .addContainerGap(838, Short.MAX_VALUE))
        );

        motherTab.addTab("stockTabe", stockTab);

        firstLayer.add(motherTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, -40, 1270, 940));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(firstLayer, javax.swing.GroupLayout.PREFERRED_SIZE, 1599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(firstLayer, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//    Hover effect on buttons
    private void recordDailySales_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordDailySales_btnMouseEntered
//        recordDailySales_btn.setBackground(Color.decode(bgHover_rgb_color));
//        recordDailySales_btn.setForeground(Color.white);
    }//GEN-LAST:event_recordDailySales_btnMouseEntered

    private void recordDailySales_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordDailySales_btnMouseExited
//        recordDailySales_btn.setBackground(Color.decode("#FFFFFF"));
//        recordDailySales_btn.setForeground(Color.black);
    }//GEN-LAST:event_recordDailySales_btnMouseExited

    private void recordPurchases_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordPurchases_btnMouseEntered
//        recordPurchases_btn.setBackground(Color.decode(bgHover_rgb_color));
//        recordPurchases_btn.setForeground(Color.white);
    }//GEN-LAST:event_recordPurchases_btnMouseEntered

    private void recordPurchases_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordPurchases_btnMouseExited
//        recordPurchases_btn.setBackground(Color.white);
//        recordPurchases_btn.setForeground(Color.black);
    }//GEN-LAST:event_recordPurchases_btnMouseExited

    private void recordExpenses_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordExpenses_btnMouseEntered
//       recordExpenses_btn.setBackground(Color.decode(bgHover_rgb_color));
//       recordExpenses_btn.setForeground(Color.white);
    }//GEN-LAST:event_recordExpenses_btnMouseEntered

    private void recordExpenses_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordExpenses_btnMouseExited
//        recordExpenses_btn.setBackground(Color.white);
//        recordExpenses_btn.setForeground(Color.black);
    }//GEN-LAST:event_recordExpenses_btnMouseExited

    private void viewWeeklyReport_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewWeeklyReport_btnMouseEntered
//        viewWeeklyReport_btn.setBackground(Color.decode(bgHover_rgb_color));
//        viewWeeklyReport_btn.setForeground(Color.white);
    }//GEN-LAST:event_viewWeeklyReport_btnMouseEntered

    private void viewWeeklyReport_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewWeeklyReport_btnMouseExited
//        viewWeeklyReport_btn.setBackground(Color.white);
//        viewWeeklyReport_btn.setForeground(Color.black);
    }//GEN-LAST:event_viewWeeklyReport_btnMouseExited

    private void viewStockSummary_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewStockSummary_btnMouseEntered
//        viewStockSummary_btn.setBackground(Color.decode(bgHover_rgb_color));
//        viewStockSummary_btn.setForeground(Color.white);
    }//GEN-LAST:event_viewStockSummary_btnMouseEntered

    private void viewStockSummary_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewStockSummary_btnMouseExited
//        viewStockSummary_btn.setBackground(Color.white);
//        viewStockSummary_btn.setForeground(Color.black);
    }//GEN-LAST:event_viewStockSummary_btnMouseExited

    private void recordDailySales_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordDailySales_btnMouseClicked
//        recordDailySales_btn.setBackground(Color.decode(bgActive_rgb_color));
//        recordDailySales_btn.setForeground(Color.white);
//        System.out.println("Works");
    }//GEN-LAST:event_recordDailySales_btnMouseClicked

    private void logout_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMouseEntered
        logout_btn.setBackground(Color.decode("#FF1300"));
    }//GEN-LAST:event_logout_btnMouseEntered

    private void logout_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMouseExited
        logout_btn.setBackground(Color.decode("#E74C3C"));
    }//GEN-LAST:event_logout_btnMouseExited

    private void logout_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMouseClicked
         JDialog dialog = new JDialog();
         dialog.setUndecorated(true); // Removes title bar (including close and minize buttons)
        
        int response = JOptionPane.showConfirmDialog(
                dialog,
                "Do you want to logout?",
                "Confirm Logout!", 
                JOptionPane.YES_NO_OPTION);
        
        if (response == JOptionPane.YES_OPTION) {
             try {
                 Thread.sleep(100); // Delay for  100 milisecods
             } catch (InterruptedException ex) {
                 System.getLogger(mainFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
             }
             
            System.exit(0); // closes the main app window
            
        } else {
//            Nothing happens
        }
    }//GEN-LAST:event_logout_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cashout_btn;
    private javax.swing.JTable dailyCashout_tbl;
    private javax.swing.JButton dashboardButton;
    private javax.swing.JLabel dashboardLabel;
    private javax.swing.JPanel dashboardTab;
    private javax.swing.JPanel firstLayer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoInFull;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JButton logout_btn;
    private javax.swing.JLabel monthly_sales_summary_label;
    private javax.swing.JTabbedPane motherTab;
    private javax.swing.JPanel navigationpanel;
    private javax.swing.JPanel recordDailySales;
    private javax.swing.JButton recordDailySales_btn;
    private javax.swing.JPanel recordExpenses;
    private javax.swing.JButton recordExpenses_btn;
    private javax.swing.JPanel recordPurchases;
    private javax.swing.JButton recordPurchases_btn;
    private javax.swing.JComboBox<String> sorting_combobox;
    private javax.swing.JPanel stockTab;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JButton viewStockSummary_btn;
    private javax.swing.JPanel viewWeeklyReport;
    private javax.swing.JButton viewWeeklyReport_btn;
    private javax.swing.JLabel weekly_cashout_summary_label;
    // End of variables declaration//GEN-END:variables
}
